Web/Client/ViewModels/Drafts/DraftDocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Web;
using Kapitalist.Data.Models.DTO;
using Kapitalist.Data.Models.Enums;
using Kapitalist.Web.Client.Interfaces;

namespace Kapitalist.Web.Client.ViewModels.Drafts
{
    public class DraftDocumentViewModel : IDraftDocumentViewModel
    {
        public Guid TenderGuid { get; set; }

        public string StringId { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }
        public string DocumentType { get; set; }
        public string Format { get; set; }
        public string Language { get; set; }
        public RelatedTo DocumentOf { get; set; }
        public string RelatedId { get; set; }

        public HttpPostedFileBase Document { get; set; }

        public DraftDocumentViewModel()
        {
        }

        public DraftDocumentViewModel(Guid tenderGuid, DraftTenderDocumentDTO draftTenderDocumentDTO)
        {
            TenderGuid = tenderGuid;
            if(draftTenderDocumentDTO != null)
            {
                StringId = draftTenderDocumentDTO.StringId;
                Description = draftTenderDocumentDTO.Description;
                Title = draftTenderDocumentDTO.Title;
                Format = draftTenderDocumentDTO.Format;
                DocumentOf = draftTenderDocumentDTO.DocumentOf;
                DocumentType = draftTenderDocumentDTO.DocumentType;
                Language = draftTenderDocumentDTO.Language;
                RelatedId = draftTenderDocumentDTO.RelatedItem;
            }
        }
        public DraftDocumentViewModel(Guid tenderGuid, DocumentDTO tenderDocumentDTO)
        {
            TenderGuid = tenderGuid;
            if(tenderDocumentDTO != null)
            {
                StringId = tenderDocumentDTO.StringId;
                Description = tenderDocumentDTO.Description;
                Title = tenderDocumentDTO.Title;
                Format = tenderDocumentDTO.Format;
                DocumentOf = tenderDocumentDTO.DocumentOf;
                DocumentType = tenderDocumentDTO.DocumentType;
                Language = tenderDocumentDTO.Language;
                RelatedId = tenderDocumentDTO.RelatedItem;
            }
        }
        

        public DraftTenderDocumentDTO ToDTO()
        {
            var documentDTO = new DraftTenderDocumentDTO
            {
                StringId = StringId,
                Description = Description,
                Title = Title,
                Format = Format,
                DocumentOf = DocumentOf,
                DocumentType = DocumentType,
                Language = Language,
                RelatedItem = RelatedId,
                TenderGuid = TenderGuid
            };
            var target = new MemoryStream();
            Document.InputStream.CopyTo(target);
            documentDTO.Data = target.ToArray();


            if (string.IsNullOrWhiteSpace(documentDTO.StringId))
            {
                documentDTO.StringId = Guid.NewGuid().ToString("N");
            }

            return documentDTO;
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Document == null || Document?.ContentLength <= 0)
            {
                yield return new ValidationResult("Докумет повинен бути присутній.", new[] { "Document" });
            }
        }
    }
}

Web/Client/ViewModels/Drafts/DraftItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Kapitalist.Data.Models.DTO;
using Kapitalist.Web.Client.Interfaces;
using Kapitalist.Web.Client.ViewModels.Base;

namespace Kapitalist.Web.Client.ViewModels.Drafts
{
    public class DraftItemViewModel : BaseItemViewModel, IDraftItemViewModel, IValidatableObject
    {
        public DraftItemViewModel()
        {
        }

        public DraftItemViewModel(Guid tenderGuid) : base(tenderGuid)
        {
        }

        public DraftItemViewModel(Guid tenderGuid, ItemDTO item) : base(tenderGuid, item)
        {
            if (item != null)
            {
                Features = item.Features?.Select(m => new FeatureViewModel(tenderGuid, m));
                Documents = item.Documents?.Select(m => new DraftDocumentViewModel(tenderGuid, m));
            }
        }

        public IEnumerable<IFeatureViewModel> Features { get; set; }
        public IEnumerable<IDraftDocumentViewModel> Documents { get; set; }

        public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var errors = base.Validate(validationContext).ToList();


            if (ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.ABOVE_THRESHOLD_EU
                || ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.ABOVE_THRESHOLD_UA
                || ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.NEGOTIATION
                || ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.NEGOTIATION_QUICK
                || ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.REPORTING
                || ProcurementMethodType == Data.Models.Consts.ProcurementMethodType.ABOVE_THRESHOLD_UA_DEFENSE)
            {
                if (DeliveryDate?.EndDate == null)
                {
                    errors.Add(new ValidationResult("Повинна бути вказана хоча б endDate дата.", new[] { "DeliveryDate.EndDate" }));
                }
                if (DeliveryAddress.IsEmpty())
                {
                    errors.Add(new ValidationResult("Адреса або місце доставки повинні бути заповнені", new[]
                {
                    "DeliveryAddress.Country",
                    "DeliveryAddress.Locality",
                    "DeliveryAddress.PostalCode",
                    "DeliveryAddress.Region",
                    "DeliveryAddress.Street",
                }));
                }
            }

            return errors;
        }
    }
}

Web/Client/Controllers/Drafts/BaseDraftController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Kapitalist.Data.Models.DTO;
using Kapitalist.Services.Prozorro.Exceptions;
using Kapitalist.Web.Client.Controllers.Base;
using Kapitalist.Web.Security;

namespace Kapitalist.Web.Client.Controllers.Drafts
{

    public class BaseDraftController : BaseController
    {
        public Lazy<IAccessManager> AccessManager { get; set; }

        public BaseDraftController()
        {
        }

        public BaseDraftController(Lazy<IAccessManager> accessManager)
        {
            AccessManager = accessManager;
        }

    }
}

Web/Client/Controllers/Drafts/DraftContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Kapitalist.Services.Prozorro.Providers;
using Kapitalist.Web.Client.ViewModels;
using Kapitalist.Web.Client.ViewModels.Drafts;
using Kapitalist.Web.Security;

namespace Kapitalist.Web.Client.Controllers.Drafts
{
    [Authorize]
    [RoutePrefix("draft")]
    public class DraftContactController : BaseDraftController
    {
        private IDraftProvider DraftProvider { get; }
        public Lazy<IProfileProvider> ProfileProvider { get; set; }

        public DraftContactController(IDraftProvider draftProvider, Lazy<IAccessManager> accessManager, Lazy<IProfileProvider> profileProvider)
            : base(accessManager)
        {
            DraftProvider = draftProvider;
            ProfileProvider = profileProvider;
        }

        [Route("tender/{tenderGuid:guid}/addContact")]
        [HttpGet]
        public async Task<ActionResult> AddContact(Guid tenderGuid)
        {
            int userOrganizationId = AccessManager.Value.UserOrganizationId;
            var contacts = await ProfileProvider.Value.GetContacts(userOrganizationId, tenderGuid);
            var viewModel = new AddContactViewModel(tenderGuid, contacts.Select(m => new ContactViewModel(tenderGuid, m)));
            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/addContact")]
        [HttpPost]
        public async Task<ActionResult> AddContact(AddContactViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            await DraftProvider.AddContact(viewModel.TenderGuid, viewModel.ContactId);
            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }


        [Route("tender/{tenderGuid:guid}/deleteContact/{contactId}")]
        [HttpPost]
        public async Task<ActionResult> DeleteContact(Guid tenderGuid, int contactId)
        {
            await DraftProvider.DeleteContact(tenderGuid, contactId);
            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = tenderGuid});
        }
    }
}

Web/Client/Controllers/Drafts/DraftDocumentController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kapitalist.Data.Models;
using Kapitalist.Data.Models.DTO;
using Kapitalist.Data.Models.Enums;
using Kapitalist.Services.Prozorro.Providers;
using Kapitalist.Web.Client.ViewModels;
using Kapitalist.Web.Client.ViewModels.Drafts;
using Kapitalist.Web.Security;

namespace Kapitalist.Web.Client.Controllers.Drafts
{
    [Authorize]
    [RoutePrefix("draft")]
    public class DraftDocumentController : BaseDraftController
    {
        private IDraftProvider DraftProvider { get; }

        public DraftDocumentController(IDraftProvider draftProvider, Lazy<IAccessManager> accessManager)
            : base(accessManager)
        {
            DraftProvider = draftProvider;
        }

        [Route("tender/{tenderGuid:guid}/addDocument/{relatedTo}/{relatedId}")]
        [HttpGet]
        public ActionResult AddDocument(Guid tenderGuid, string relatedId, RelatedTo relatedTo)
        {
            var viewModel = new DraftDocumentViewModel()
            {
                TenderGuid = tenderGuid,
                RelatedId = relatedId == tenderGuid.ToString("N") ? null : relatedId,
                DocumentOf = relatedTo
            };

            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/addDocument/{relatedTo}/{relatedId}")]
        [HttpPost]
        public async Task<ActionResult> AddDocument(DraftDocumentViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var documentDTO = viewModel.ToDTO();

            await DraftProvider.AddDraftDocument(viewModel.TenderGuid, documentDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new { tenderGuid = viewModel.TenderGuid });
        }

        [Route("tender/{tenderGuid:guid}/editDocument/{documentId}")]
        [HttpGet]
        public async Task<ActionResult> EditDocument(Guid tenderGuid, string documentId)
        {
            var draftTenderDocumentDTO = await DraftProvider.GetDraftDocument(tenderGuid, documentId);

            var viewModel = new DraftDocumentViewModel(tenderGuid, draftTenderDocumentDTO);
            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/editDocument/{documentId}")]
        [HttpPost]
        public async Task<ActionResult> EditDocument(DraftDocumentViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var documentDTO = viewModel.ToDTO();
            await DraftProvider.EditDraftDocument(viewModel.TenderGuid, documentDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }

        [Route("tender/{tenderGuid:guid}/deleteDocument/{documentId}")]
        [HttpPost]
        public async Task<ActionResult> DeleteDocument(Guid tenderGuid, string documentId)
        {
            await DraftProvider.DeleteDraftDocument(tenderGuid, documentId);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = tenderGuid});
        }
    }
}

Web/Client/Controllers/Drafts/DraftFeatureController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kapitalist.Data.Models;
using Kapitalist.Services.Prozorro.Providers;
using Kapitalist.Web.Client.ViewModels;
using Kapitalist.Web.Security;

namespace Kapitalist.Web.Client.Controllers.Drafts
{
    [Authorize]
    [RoutePrefix("draft")]
    public class DraftFeatureController : BaseDraftController
    {
        public DraftFeatureController(IDraftProvider draftProvider, Lazy<IAccessManager> accessManager)
            : base(accessManager)
        {
            DraftProvider = draftProvider;
        }

        private IDraftProvider DraftProvider { get; }

        [Route("tender/{tenderGuid:guid}/addFeature/{type}/{relatedId}")]
        [HttpGet]
        public async Task<ActionResult> AddFeature(Guid tenderGuid, FeatureType type, string relatedId)
        {
            var tender = await DraftProvider.GetDraftTender(tenderGuid);

            var viewModel = new FeatureViewModel
            {
                TenderGuid = tenderGuid,
                RelatedItem = relatedId,
                Type = type
            };
            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/addFeature/{type}/{relatedId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddFeature(FeatureViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var featureDTO = viewModel.ToDTO();
            var featureStringId = await DraftProvider.AddDraftFeature(viewModel.TenderGuid, featureDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }

        [Route("tender/{tenderGuid:guid}/editFeature/{featureId}")]
        [HttpGet]
        public async Task<ActionResult> EditFeature(Guid tenderGuid, string featureId)
        {
            var tender = await DraftProvider.GetDraftTender(tenderGuid);
            var feature = await DraftProvider.GetDraftFeature(tenderGuid, featureId);

            var viewModel = new FeatureViewModel(tenderGuid, feature);

            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/editFeature/{featureId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditFeature(FeatureViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var featureDTO = viewModel.ToDTO();
            await DraftProvider.EditDraftFeature(viewModel.TenderGuid, featureDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }

        [Route("tender/{tenderGuid:guid}/deleteFeature/{featureId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteFeature(Guid tenderGuid, string featureId)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("EditFeature",
                    new {tenderGuid, featureId});
            }

            await DraftProvider.DeleteFeature(tenderGuid, featureId);
            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid});
        }


        [Route("tender/{tenderGuid:guid}/addFeatureEU/{type}/{relatedId}")]
        [HttpGet]
        public async Task<ActionResult> AddFeatureEU(Guid tenderGuid, FeatureType type, string relatedId)
        {
            var tender = await DraftProvider.GetDraftTender(tenderGuid);

            var viewModel = new FeatureEUViewModel
            {
                TenderGuid = tenderGuid,
                RelatedItem = relatedId,
                Type = type
            };
            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/addFeatureEU/{type}/{relatedId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddFeatureEU(FeatureEUViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var featureDTO = viewModel.ToDTO();
            var featureStringId = await DraftProvider.AddDraftFeature(viewModel.TenderGuid, featureDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }

        [Route("tender/{tenderGuid:guid}/editFeatureEU/{featureId}")]
        [HttpGet]
        public async Task<ActionResult> EditFeatureEU(Guid tenderGuid, string featureId)
        {
            var tender = await DraftProvider.GetDraftTender(tenderGuid);
            var feature = await DraftProvider.GetDraftFeature(tenderGuid, featureId);

            var viewModel = new FeatureEUViewModel(tenderGuid, feature);

            return View(viewModel);
        }

        [Route("tender/{tenderGuid:guid}/editFeatureEU/{featureId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditFeatureEU(FeatureEUViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var featureDTO = viewModel.ToDTO();
            await DraftProvider.EditDraftFeature(viewModel.TenderGuid, featureDTO);

            return RedirectToAction("Info", "DraftTenderInfo", new {tenderGuid = viewModel.TenderGuid});
        }
    }
}

Web/Client/Views/Drafts/DraftDocument/AddDocument.cshtml
@using Kapitalist.Web.Framework.Helpers.Enums
@using Kapitalist.Web.Resources
@model Kapitalist.Web.Client.ViewModels.Drafts.DraftDocumentViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container header-and-body-content">
    <h2>@GlobalRes.AddDocument.</h2>

    @using (Html.BeginForm("AddDocument", "DraftDocument", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.TenderGuid)
        @Html.HiddenFor(m => m.DocumentOf)
        @Html.HiddenFor(m => m.RelatedId)


        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Title</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Title, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Description</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Description, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.DocumentType</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.DocumentType, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DocumentType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Format</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Format, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Format, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Language</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Language, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Language, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label class="col-md-3 control-label">@GlobalRes.Document</label>
            <div class="col-md-9">
                <input type="file" name="@Html.NameFor(m => m.Document)" id="@Html.IdFor(m => m.Document)"class="btn btn-default" />
                @Html.ValidationMessageFor(m => m.Document, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="col-md-offset-3 col-md-9">
            <a href="@Url.Action("Info", "DraftTenderInfo", new {tenderGuid = Model.TenderGuid})" class="btn btn-default col-xs-12 col-md-3 square-background-yellow btn-lg">@GlobalRes.Cancel</a>
            <input type="submit" value="@GlobalRes.Save" class="btn btn-default col-xs-12 col-md-3 square-background-blue btn-lg" />
        </div>
    }
</div>

Web/Client/Views/Drafts/DraftDocument/EditDocument.cshtml
@using System.Web.Mvc.Html
@model Kapitalist.Web.Client.ViewModels.Drafts.DraftDocumentViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container header-and-body-content">
    <h2>@GlobalRes.EditDocument.</h2>

    @using (Html.BeginForm("EditDocument", "DraftDocument", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.TenderGuid)
        @Html.HiddenFor(m => m.StringId)
        @Html.HiddenFor(m => m.DocumentOf)
        @Html.HiddenFor(m => m.RelatedId)


        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Title</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Title, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Description</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Description, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.DocumentType</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.DocumentType, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DocumentType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Format</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Format, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Format, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">@GlobalRes.Language</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Language, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Language, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label class="col-md-3 control-label">@GlobalRes.Document</label>
            <div class="col-md-9">
                <input type="file" name="@Html.NameFor(m => m.Document)" id="@Html.IdFor(m => m.Document)" class="btn btn-default" />
                @Html.ValidationMessageFor(m => m.Document, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="col-md-offset-3 col-md-9">
            <a href="@Url.Action("Info", "DraftTenderInfo", new {tenderGuid = Model.TenderGuid})" class="btn btn-default col-xs-12 col-md-3 square-background-yellow btn-lg">@GlobalRes.Cancel</a>
            <input type="submit" value="@GlobalRes.Save" class="btn btn-default col-xs-12 col-md-3 square-background-blue btn-lg" />
        </div>
    }
</div>